// ServiceCost.js

const SERVICE_COST = [
  // POPCORN / CEILINGS
  {
    id: "popcorn-unpainted-sf",
    section: "sec-popcorn",
    name: "Popcorn removal + Level 5 (unpainted)",
    desc: "Remove texture, Level 5 skim, HEPA sand, prime & paint-ready.",
    unit: "sf",
    rate: 6.5,
    defaultQty: null,
  },
  {
    id: "popcorn-painted-sf",
    section: "sec-popcorn",
    name: "Popcorn removal + Level 5 (painted)",
    desc: "Remove painted texture, repair joints, Level 5 finish.",
    unit: "sf",
    rate: 7.5,
    defaultQty: null,
  },
  {
    id: "popcorn-stairwell-job",
    section: "sec-popcorn",
    name: "Stairwell / high ceiling popcorn removal",
    desc: "Includes scaffold / ladders, full containment & cleanup.",
    unit: "job",
    rate: 2200,
    defaultQty: 1,
  },
  {
    id: "popcorn-standard-room-job",
    section: "sec-popcorn",
    name: "Popcorn removal + Level 5 — standard room (up to ~140 sf)",
    desc: "All-in room package: removal, Level 5 skim, HEPA sand, prime.",
    unit: "room",
    rate: 1100,
    defaultQty: 1,
  },
  {
    id: "popcorn-large-room-job",
    section: "sec-popcorn",
    name: "Popcorn removal + Level 5 — large room (140–220 sf)",
    desc: "Open concept / large rooms, extra containment & access.",
    unit: "room",
    rate: 1500,
    defaultQty: 1,
  },
  {
    id: "popcorn-spot-repair",
    section: "sec-popcorn",
    name: "Popcorn ceiling repair — localized patch",
    desc: "Scrape, skim & blend small damaged areas into existing texture.",
    unit: "ea",
    rate: 260,
    defaultQty: 1,
  },

  // PAINT — WALLS / ROOMS
  {
    id: "walls-standard-room",
    section: "sec-paint",
    name: "Interior walls — standard bedroom",
    desc: "2 coats on walls, light prep, low-VOC pro paint.",
    unit: "room",
    rate: 450,
    defaultQty: 1,
  },
  {
    id: "walls-large-room",
    section: "sec-paint",
    name: "Interior walls — large room",
    desc: "Family/Living room, 2 coats, basic repairs.",
    unit: "room",
    rate: 650,
    defaultQty: 1,
  },
  {
    id: "walls-master-bedroom",
    section: "sec-paint",
    name: "Interior walls — master bedroom",
    desc: "Larger bedroom with extra cut-ins, 2 coats premium paint.",
    unit: "room",
    rate: 700,
    defaultQty: 1,
  },
  {
    id: "walls-hallway-stair",
    section: "sec-paint",
    name: "Hallway / staircase walls",
    desc: "Walls along stairs / halls; includes access setup & handrail masking.",
    unit: "job",
    rate: 950,
    defaultQty: 1,
  },
  {
    id: "walls-bathroom",
    section: "sec-paint",
    name: "Bathroom walls",
    desc: "Moisture-resistant paint, fixture & fan masking, 2 coats.",
    unit: "room",
    rate: 380,
    defaultQty: 1,
  },
  {
    id: "walls-accent-wall",
    section: "sec-paint",
    name: "Feature / accent wall",
    desc: "1 wall up to ~12' wide, 2 coats accent colour.",
    unit: "wall",
    rate: 220,
    defaultQty: 1,
  },
  {
    id: "walls-by-sf",
    section: "sec-paint",
    name: "Interior walls — by sq ft",
    desc: "Use for open areas; 2 coats on walls with standard prep.",
    unit: "sf",
    rate: 2.75,
    defaultQty: null,
  },

  // PAINT — CEILINGS
  {
    id: "ceiling-room",
    section: "sec-paint",
    name: "Ceiling paint — room",
    desc: "Prime as needed + 2 coats ceiling white.",
    unit: "room",
    rate: 220,
    defaultQty: 1,
  },
  {
    id: "ceiling-bathroom",
    section: "sec-paint",
    name: "Ceiling paint — bathroom",
    desc: "Bathroom ceiling with moisture-resistant paint, 2 coats.",
    unit: "room",
    rate: 160,
    defaultQty: 1,
  },
  {
    id: "ceiling-hallway",
    section: "sec-paint",
    name: "Ceiling paint — hallway / entry",
    desc: "Hall / foyer ceiling incl. cut-ins around fixtures.",
    unit: "job",
    rate: 260,
    defaultQty: 1,
  },
  {
    id: "ceiling-by-sf",
    section: "sec-paint",
    name: "Ceiling paint — by sq ft",
    desc: "Flat ceilings, 1–2 coats ceiling white.",
    unit: "sf",
    rate: 1.5,
    defaultQty: null,
  },

  // PAINT — DOORS / WINDOWS
  {
    id: "door-frame",
    section: "sec-paint",
    name: "Door & frame (per door)",
    desc: "Spot-sand, caulk, 2 coats semi-gloss.",
    unit: "door",
    rate: 90,
    defaultQty: 1,
  },
  {
    id: "door-slab-only",
    section: "sec-paint",
    name: "Door only (no frame)",
    desc: "Both sides of interior door slab, light sand & 2 coats.",
    unit: "door",
    rate: 70,
    defaultQty: 1,
  },
  {
    id: "closet-bifold-doors",
    section: "sec-paint",
    name: "Closet bifold / slider doors",
    desc: "2-panel bifold or slider set, both sides, 2 coats semi-gloss.",
    unit: "set",
    rate: 140,
    defaultQty: 1,
  },
  {
    id: "window-and-casing",
    section: "sec-paint",
    name: "Window + interior casing",
    desc: "Interior sash (if paintable), stools & casing, 2 coats.",
    unit: "window",
    rate: 130,
    defaultQty: 1,
  },

  // PAINT — TRIM & DETAILS
  {
    id: "trim-baseboards",
    section: "sec-paint",
    name: "Baseboards / trim",
    desc: "Caulk joints, light sand, 2 coats semi-gloss.",
    unit: "lf",
    rate: 5,
    defaultQty: null,
  },
  {
    id: "trim-casing",
    section: "sec-paint",
    name: "Door / window casing",
    desc: "Perimeter casing around doors/windows, caulk + 2 coats.",
    unit: "lf",
    rate: 4.5,
    defaultQty: null,
  },
  {
    id: "trim-crown",
    section: "sec-paint",
    name: "Crown moulding",
    desc: "Mask ceilings/walls, 2 coats semi-gloss on crown.",
    unit: "lf",
    rate: 7.5,
    defaultQty: null,
  },
  {
    id: "trim-wainscoting",
    section: "sec-paint",
    name: "Wainscoting / wall panels",
    desc: "Panels, rails & stiles; detailed brush/roller work, 2 coats.",
    unit: "lf",
    rate: 10,
    defaultQty: null,
  },
  {
    id: "railings-spindles",
    section: "sec-paint",
    name: "Stair railings & spindles",
    desc: "Handrail & spindles; detail sanding + 2 coats enamel.",
    unit: "job",
    rate: 650,
    defaultQty: 1,
  },
  {
    id: "closet-small-paint",
    section: "sec-paint",
    name: "Closet — small (walls & ceiling)",
    desc: "Standard reach-in closet, walls & ceiling, 2 coats.",
    unit: "closet",
    rate: 140,
    defaultQty: 1,
  },
  {
    id: "closet-walkin-paint",
    section: "sec-paint",
    name: "Closet — walk-in",
    desc: "Walk-in closet, walls & ceiling, shelving masked, 2 coats.",
    unit: "closet",
    rate: 260,
    defaultQty: 1,
  },

  // PAINT PACKAGES — FULL ROOM / HOME
  {
    id: "paintpkg-bedroom-standard",
    section: "sec-paint",
    name: "Full repaint — standard bedroom (walls, ceiling, trim, 1 door)",
    desc: "Complete bedroom: walls, ceiling, baseboards, casing & 1 door; 2 coats on walls/trim, 1–2 on ceiling.",
    unit: "room",
    rate: 980,
    defaultQty: 1,
  },
  {
    id: "paintpkg-bedroom-master",
    section: "sec-paint",
    name: "Full repaint — master bedroom (walls, ceiling, trim, 2 doors)",
    desc: "Larger bedroom including ceiling, baseboards, casings & up to 2 doors.",
    unit: "room",
    rate: 1350,
    defaultQty: 1,
  },
  {
    id: "paintpkg-living-dining",
    section: "sec-paint",
    name: "Full repaint — living / dining room",
    desc: "Open living/dining area; walls, ceiling, baseboards, window trim & 1–2 doors.",
    unit: "room",
    rate: 1500,
    defaultQty: 1,
  },
  {
    id: "paintpkg-bathroom-full",
    section: "sec-paint",
    name: "Full repaint — bathroom (walls, ceiling, trim & door)",
    desc: "Moisture-resistant paint on walls & ceiling, plus door & trim.",
    unit: "room",
    rate: 520,
    defaultQty: 1,
  },
  {
    id: "paintpkg-condo-by-sf",
    section: "sec-paint",
    name: "Full interior repaint — by sq ft (walls,  trim & doors)",
    desc: "Whole interior package: walls, ceilings, baseboards, doors, frames & closets.",
    unit: "sf",
    rate: 3.75,
    defaultQty: null,
  },
  {
    id: "paintpkg-condo-by-sf",
    section: "sec-paint",
    name: "Full interior repaint — walls only)",
    desc: "Whole interior package: baseboards.",
    unit: "sf",
    rate: 3.0,
    defaultQty: null,
  },
  // DRYWALL / EXTRA
  {
    id: "drywall-small-patch",
    section: "sec-add",
    name: "Drywall repair — small patch",
    desc: "Fill small hole/crack, sand & prime ready for paint.",
    unit: "ea",
    rate: 120,
    defaultQty: 1,
  },
  {
    id: "drywall-large-patch",
    section: "sec-add",
    name: "Drywall repair — large / multiple patches",
    desc: "Cut out damaged board, re-board, tape, mud & sand.",
    unit: "ea",
    rate: 220,
    defaultQty: 1,
  },
  {
    id: "corner-bead",
    section: "sec-add",
    name: "Corner bead supply & install",
    desc: "Metal/vinyl beads, mud, sand, straighten corners.",
    unit: "lf",
    rate: 12,
    defaultQty: null,
  },
  {
    id: "debris-disposal",
    section: "sec-add",
    name: "Debris disposal",
    desc: "Bag & remove site waste / popcorn debris.",
    unit: "job",
    rate: 120,
    defaultQty: 1,
  },

  // GENERIC
  {
    id: "site-protection",
    section: "any",
    name: "Site protection & masking",
    desc: "Floors, stairs & key furniture protection (poly/RamBoard).",
    unit: "job",
    rate: 180,
    defaultQty: 1,
  },
];

export default SERVICE_COST;
